name: flutter_gherkin
description: A Gherkin / Cucumber parser and test runner for Dart and Flutter
version: 3.0.0-rc.9
homepage: https://github.com/jonsamwell/flutter_gherkin

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  analyzer: ">=1.7.1 <9.0.0"
  collection: ^1.15.0
  gherkin: ^2.0.8
  source_gen: ^3.1.0
  build: ^3.0.2
  glob: ^2.0.2
  # gherkin:
    # path: ../dart_gherkin

dev_dependencies:
  meta: ^1.7.0 
  lints: ^6.0.0
  build_config: ^1.0.0

flutter:
